server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-Register
          uri: lb://ms-Register
          predicates:
            - Path=/api/users/**


        - id: ms-Request
          uri: lb://ms-Request
          predicates:
            - Path=/api/credit/**


        - id: ms-Documents
          uri: lb://ms-Documents
          predicates:
            - Path=/api/documents/**


        - id: ms-Simulate
          uri: lb://ms-Simulate
          predicates:
            - Path=/simulate/**


        - id: ms-Evaluation
          uri: lb://ms-Evaluation
          predicates:
            - Path=/api/evaluation/**

